name: pure_mixpanel
description: A new pure Dart library for Mixpanel analytics.
version: 1.0.0
author: Nicholas Manning <puremixpanel@gmail.com>
homepage: https://www.twitter.com/seenickcode

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.5
  http: ^0.11.3+16
  test: ^0.12.37

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=1.19.0 <2.0.0'
  flutter: '>=0.1.2'